### ISSUE TITLE
PHP Strict Standards:  Only variables should be passed by reference

### ISSUE THREAD

**Issue by ken-muturi** [discophp/framework#1]
so-l047:disco-php Beloved$ php disco db-restore-structure

PHP Strict Standards:  Only variables should be passed by reference in /Users/Beloved/Sites/PHP/disco-php/vendor/discophp/framework/core/classes/App.class.php on line 150

Strict Standards: Only variables should be passed by reference in /Users/Beloved/Sites/PHP/disco-php/vendor/discophp/framework/core/classes/App.class.php on line 150
PHP Fatal error:  Uncaught exception 'Exception' with message 'Config key `DEV_MODE` does not exist!' in /Users/Beloved/Sites/PHP/disco-php/vendor/discophp/framework/core/classes/App.class.php:317
Stack trace:
#0 /Users/Beloved/Sites/PHP/disco-php/vendor/discophp/framework/core/classes/App.class.php(177): Disco\classes\App->config('DEV_MODE')
#1 /Users/Beloved/Sites/PHP/disco-php/vendor/discophp/framework/core/classes/App.class.php(123): Disco\classes\App->__construct(NULL, NULL)
#2 /Users/Beloved/Sites/PHP/disco-php/disco(10): Disco\classes\App::instance()
#3 {main}

  thrown in /Users/Beloved/Sites/PHP/disco-php/vendor/discophp/framework/core/classes/App.class.php on line 317

Fatal error: Uncaught exception 'Exception' with message 'Config key `DEV_MODE` does not exist!' in /Users/Beloved/Sites/PHP/disco-php/vendor/discophp/framework/core/classes/App.class.php:317
Stack trace:
#0 /Users/Beloved/Sites/PHP/disco-php/vendor/discophp/framework/core/classes/App.class.php(177): Disco\classes\App->config('DEV_MODE')
#1 /Users/Beloved/Sites/PHP/disco-php/vendor/discophp/framework/core/classes/App.class.php(123): Disco\classes\App->__construct(NULL, NULL)
#2 /Users/Beloved/Sites/PHP/disco-php/disco(10): Disco\classes\App::instance()
#3 {main}

  thrown in /Users/Beloved/Sites/PHP/disco-php/vendor/discophp/framework/core/classes/App.class.php on line 317

**Comment by jbhamilton** [comment]
What version is this on? The stand alone `disco` executable was deprecated as of version 3.0.0 and the CLI syntax now works like:
`php public/index.php db-restore 'app/db/' 'YOUR_STRUCTURE_FILE'`
See http://discophp.com/docs/command-line-interface for more information on the CLI.

It appears your using a [project wrapper](https://github.com/discophp/project) that was for versions pre 3.0.0 and a version of the framework that is 3.0.0 or later. You're using at least using version 3.0.2 as this is when exceptions starting being thrown when accessing config keys that don't exist.
